config/routes.rb
RailsWebsite::Application.routes.draw do
  root  'main_pages#home'
  match '/resume',    to: 'main_pages#resume',    via: 'get'
  match '/code',    to: 'main_pages#code',    via: 'get'
  match '/talks',    to: 'main_pages#talks',    via: 'get'
  match '/blog',    to: 'main_pages#blog',    via: 'get'
  match '/contact',    to: 'main_pages#contact',    via: 'get'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greg Sandell</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
	<div id="header">
		<div id="logo">
			<h1><a href="http://www.gregsandell.com">Greg Sandell</a></h1>
			<h2>Javascript Web App Developer</h2>
		</div>
		<div id="menu">
            <% current_uri = request.env['PATH_INFO'] %>
			<ul>
				<li class="<%= current_uri == '/' ? 'active' : ''%>"><%= link_to "Home", root_path %></li>
                <li class="<%= current_uri == '/resume' ? 'active' : ''%>"><%= link_to "Resume", resume_path %></li>
				<li class="<%= current_uri == '/code' ? 'active' : ''%>"><%= link_to "Code", code_path %></li>
				<li class="<%= current_uri == '/talks' ? 'active' : ''%>"><%= link_to "Talks", talks_path %></li>
				<li class="<%= current_uri == '/blog' ? 'active' : ''%>"><%= link_to "Blog", blog_path %></li>
				<li class="<%= current_uri == '/contact' ? 'active' : ''%>"><%= link_to "Contact", contact_path %></li>
			</ul>
		</div>
    </div>
	<div id="page">
		<div id="content">
			<div id="welcome"> 
                <%= yield %>
            </div>
        </div>
		<!-- end div#content -->
		<div id="sidebar">
		    <%= yield :sidebar %>
		</div>
		<!-- end div#sidebar -->
		<div style="clear: both; height: 1px"></div>
    </div>
	<div id="footer">
		<p id="legal">Copyright &copy; 2007 Greg Sandell. All Rights Reserved. 
		<br/>Page Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
	</div>
</div>

</body>
</html>